### ISSUE TITLE
Logging Code

### ISSUE THREAD

**Issue by alexanderWallrabenstein** [pirminrehm/neddit#11]
Every data base operating (apart from read) must be logged in a logging file

**Comment by pirminrehm** [comment]
Current status:
Every GET/POST/... Request to the server is logged, with response-code and url. In addition everything assigned to console.log is logged, too.
Is this enough?

**Comment by alexanderWallrabenstein** [comment]
Is the date and time included?
Is the logging information written to a log file?

**Comment by pirminrehm** [comment]
[ ] File
[ ] Timestamp
