### ISSUE TITLE
user defined Hooks

### ISSUE THREAD

**Issue by alexanderWallrabenstein** [pirminrehm/neddit#13]
Allow the user to execute user defined scripts when certain actions are executed.

**Comment by pirminrehm** [comment]
Functionality on server is ipmlemented, use `/ssh/:token/start` to execute a file on neddit-test.
Server will respond:

Success:
```
"message" : Script finished successfull."
```

Failures:
```
"error" : "Script had problems, did not finished successfull"
"error" : "Script had problems, timeout after {tresholdTime} ms"
"error": "Wrong token"
