### ISSUE TITLE
Multi types for host

### ISSUE THREAD

**Issue by alexanderWallrabenstein** [pirminrehm/neddit#17]
A host must be able to have multiple types.

**Comment by pirminrehm** [comment]
Instead a schema change we could define a new type instead of adding two or more types? @alexanderWallrabenstein

**Comment by alexanderWallrabenstein** [comment]
Good idea. We have to ask which "multi types" are reasonable.

**Comment by alexanderWallrabenstein** [comment]
A user can now create own types in the config tab
