### ISSUE TITLE
route to switch to exam mode

### ISSUE THREAD

**Issue by alexanderWallrabenstein** [pirminrehm/neddit#32]
implement a route to enable or disable exam mode meaning that all hosts have to be switched between network .6 and .7 
``PUT /net/:token/exam/:bool ``
:bool = true || false

**Comment by pirminrehm** [comment]
@alexanderWallrabenstein 
You forgot the unit to set in exam mode. The correct route should look like:
`/net/:token/exam/:bool/unit/:unit`
For Requests without data to send i prefere to use `GET`
*Get an unit to exam mode*

**Comment by pirminrehm** [comment]
ToDo: 
- [ ] new tests
- [ ] change config
- [ ] implement controller
- [ ] update insterHostmaster
