### ISSUE TITLE
Order of Networks at `All Hosts` and `Networks`

### ISSUE THREAD

**Issue by pirminrehm** [pirminrehm/neddit#33]
The networks aren't ordered by their ip currently.
How it is:
- 192.168.15.0
- 141.62.73.0
- 141.62.73.32
- 192.168.111.0
- 192.168.144.0
- 192.168.5.0

How it should be:
- 141.62.73.0
- 141.62.73.32
- 192.168.5.0
- 192.168.15.0
- 192.168.111.0
- 192.168.144.0

Progress:
- [x] Ordered by full ip-address at `Networks`
- [x] Ordered by full ip-address at `All Hosts`
- [x] Ordered by full ip-address at `Save and move host` - Modal

**Comment by alexanderWallrabenstein** [comment]
Check out the clickable table headers.
Better @pirminrehm ?

**Comment by pirminrehm** [comment]
Better, but not satisfying. @alexanderWallrabenstein

**Comment by pirminrehm** [comment]
The sort in the `Save and move host` - modal is not implemented, too.

**Comment by alexanderWallrabenstein** [comment]
Done.
