### ISSUE TITLE
Comments for execute script

### ISSUE THREAD

**Issue by pirminrehm** [pirminrehm/neddit#52]
Possibility to add a comment, when the script gets executed. The comment would be visible in the logs (client).
@alexanderWallrabenstein, what's your opinion?

**Comment by alexanderWallrabenstein** [comment]
Good idea. Therefore we need a new mongoose model? And of course new routes get and post?

**Comment by pirminrehm** [comment]
No, i'll just have to change the controller and on the client a json has to be send :)
`{"comment" : "here comment"}`
- [ ] update server controller
- [ ] update client execute script
- [ ] update client show log details
